name: Conjur-Authn-JWT
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Testing before main script
        run: |
          JWT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          echo "JWT token in base64 encode:"
          echo $JWT_TOKEN | base64
      - name: Fetching secrets from conjur
        uses: cyberark/conjur-action@v2.0.2
        with:
          url: https://conjur.home.huydo.net
          account: DEMO
          authn_id: github
          secrets: test/host1/user|TEST_USER;test/host1/pass|TEST_PASS
      - name: Checking the result
        run: |
          echo Show env detail:
          env | grep TEST
          echo "$TEST_USER:$TEST_PASS" | base64
